//
// Created by mochal on 04.12.2021.
//

#ifndef TICKETMANAGER_UNHANDLEDARGUMENTEXCEPTION_H
#define TICKETMANAGER_UNHANDLEDARGUMENTEXCEPTION_H


class UnhandledArgumentException {

};


#endif //TICKETMANAGER_UNHANDLEDARGUMENTEXCEPTION_H
